### ISSUE TITLE
Enable folke/todo-comments in folke/trouble and telescope

### ISSUE THREAD

**Issue by Johnsoct** [Johnsoct/vim#20]
https://github.com/folke/trouble.nvim
https://github.com/folke/todo-comments.nvim

- [x] Trouble reporting todo-comments
- [x] Statusline component enabled
- [x] Quickfix
- [x] Quickfix keymap for Trouble working without running :Trouble [15] first
